# Generated by Django 4.0.6 on 2023-11-03 10:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coordinate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Alarm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('medium', models.CharField(choices=[('ROAD', 'ROAD'), ('RAIL', 'RAIL'), ('FLIGHT', 'FLIGHT')], max_length=10)),
                ('place', models.CharField(max_length=50)),
                ('triggered', models.BooleanField(default=False)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_at', to='alarm.coordinate')),
                ('origin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alarm_from', to='alarm.coordinate')),
            ],
        ),
    ]
